services:
  api:
    build:
      context: ./vknyvz-api
      dockerfile: Dockerfile
    container_name: vknyvz-api
    ports:
      - "5002:5000"
    volumes:
      - ./vknyvz-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
      - OPEN_WEATHER_MAP_API_KEY=${OPEN_WEATHER_MAP_API_KEY}
    command: npm run dev
    networks:
      - vknyvz-net

  web:
    build:
      context: ./vknyvz-web
      dockerfile: Dockerfile
    container_name: vknyvz-web
    ports:
      - "3002:3000"
    volumes:
      - ./vknyvz-web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-next:*}
      - NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV:-development}
    depends_on:
      - api
    command: npm run dev
    networks:
      - vknyvz-net

networks:
  vknyvz-net:
    driver: bridge
