FROM node:20.20.0-alpine3.23

WORKDIR /app

COPY vknyvz-web/package*.json ./

RUN npm ci

COPY vknyvz-web/ .
COPY .env.production .env.local

RUN npm run build
RUN npm prune --omit=dev

EXPOSE 3000

CMD ["npm", "start"]
